Track number of open file descriptors
After adding the sandbox support, I'm getting not-infrequent EMFILE
errors, which appears to be due to too many open file descriptors.
This logging is to try to track that down.

domain.js:66
    throw er;
          ^
Error: accept EMFILE
    at errnoException (net.js:769:11)
    at TCP.onconnection (net.js:1017:24)